default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: dell
  password: 123456
  host: 'localhost'
  port: 5432

development:
  <<: *default
  database: cm_dev

test:
  <<: *default
  database: cm_test

production:
  <<: *default
  database: cm_prod